### ISSUE TITLE
Memory leak 

### ISSUE THREAD

**Issue by zakariazuck** [longshoreman-portfolio/portfolio2.0.0#79]
> **Animation  is laggy after few cycles  !**

**Comment by Dun-sin** [comment]
It would be great to add your portfolio link to the about section, so people can at least know what they are working with

**Comment by zakariazuck** [comment]
oh sorry this should be  private 😅

**Comment by zakariazuck** [comment]
### The issue : 
- Animation is laggy after few cycles !

### The cause : 
- calling the `createWheelStopListener( )` function every iteration of the animation, equivalent to 60 times a second.

### Fix : 
- Remove the function `createWheelStopListener( )` from the animation scoop.
