### ISSUE TITLE
When scrolling on mobile the models jumps back

### ISSUE THREAD

**Issue by longshoremanzuck** [longshoreman-portfolio/portfolio2.0.0#97]
This happens because the state of the model is not Updated when scrolling

**Comment by zakariazuck** [comment]
### Steps to reproduce
When scrolling more than a margin twice or more.

### Expected
We anticipate that the scroll will continue where it left off.

 ### Actual results
When scrolling the jumps back or forward by N time. where N is the number of margins exceeds two.

### Reason
The reason why the function `distanceToTargetPosition (margin, currentScroll)` does not count the time when we go beyond the margin.
